env:
  es2021: true
  node: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  semi: [2, "always"],
  no-unused-vars: 0,
  import/no-unresolved: 0,
  no-shadow: 0,
  no-underscore-dangle: 0,
  class-methods-use-this: 0,
  no-console: 0,
  no-plusplus: 0,
  no-nested-ternary: 0,
  no-unused-expressions: 0,
  import/extensions: 0,
  import/order: [
    'error',
    {
      alphabetize: {
        order: 'asc',
      },
      groups: [
        'builtin',
        'external',
        'index',
        'internal',
        'parent',
        'sibling',
      ],
    }
  ],
  sort-keys: [
    'error',
    'asc',
    {
      caseSensitive: true,
      minKeys: 2,
      natural: false,
    },
  ],
  sort-vars: [
    'error',
  ],
}
